[package]
authors = []
edition = "2018"
name = "rust-wasm-test-service"
publish = false
version = "0.1.0"

[dependencies]
fastly = "0.8.3"
rust-stemmers = "1.2.0"
serde = "1.0.136"
serde_json = "1.0.79"

[profile]

[profile.release]
debug = 1
